In [1]:
!pip install nashpy

You should consider upgrading via the 'pip install --upgrade pip' command.


In [2]:
import nashpy as nash
A = [[3, 1], [0, 2]]
B = [[2, 1], [0, 3]]

In [3]:
battle_of_the_sexes = nash.Game(A, B)
battle_of_the_sexes

Bi matrix game with payoff matrices:

Row player:
[[3 1]
 [0 2]]

Column player:
[[2 1]
 [0 3]]

In [4]:
A = [[3, 0], [5, 1]]
B = [[3, 5], [0, 1]]
prisoners_dilemma = nash.Game(A, B)
prisoners_dilemma

Bi matrix game with payoff matrices:

Row player:
[[3 0]
 [5 1]]

Column player:
[[3 5]
 [0 1]]

In [5]:
A = [[1, -1], [-1, 1]]
B = [[-1, 1], [1, -1]]
matching_pennies = nash.Game(A, B)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [6]:
import numpy as np

In [7]:
np.add(A,B)

array([[0, 0],
       [0, 0]])

In [8]:
A = [[1, -1], [-1, 1]]
matching_pennies = nash.Game(A)
matching_pennies

Zero sum game with payoff matrices:

Row player:
[[ 1 -1]
 [-1  1]]

Column player:
[[-1  1]
 [ 1 -1]]

In [9]:
A = np.array([[1, -1], [-1, 1]])
B = np.array([[-1, 1], [1, -1]])


In [10]:
sigma_r = np.array([.2, .8])
sigma_c = np.array([.6, .4])
np.dot(sigma_r, np.dot(A, sigma_c)), np.dot(sigma_r, np.dot(B, sigma_c))

(-0.11999999999999998, 0.11999999999999998)

In [9]:
import nashpy as nash
matching_pennies = nash.Game(A, B)
matching_pennies[sigma_r, sigma_c]

array([-0.12,  0.12])