In [2]:
import numpy as np

In [3]:
lists = [2,3,4,5]

In [4]:
arr = np.array(lists)

In [5]:
arr

array([2, 3, 4, 5])

In [7]:
arr.shape

(4,)

In [8]:
# creating a 5 X 3 multi dimensional array
marray = np.arange(15).reshape(5,3)

marray

In [9]:
# creating a 5 X 3 multi dimensional array
marray = np.arange(15).reshape(5,3)

In [10]:
marray

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
marray > 15

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]], dtype=bool)

marray.ravel()

In [14]:
marray.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

    np.ones

In [17]:
np.ones(3)

array([ 1.,  1.,  1.])

In [18]:
ones3 = np.ones(3)

In [19]:
ones3

array([ 1.,  1.,  1.])

In [24]:
np.diag(ones3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [25]:
np.diag(ones3)*5

array([[ 5.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0.,  5.]])

In [28]:
 np.diag(ones3)*5

array([[ 5.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0.,  5.]])

In [29]:
ones3

array([ 1.,  1.,  1.])

In [30]:
np.triu(ones3)

array([[ 1.,  1.,  1.],
       [ 0.,  1.,  1.],
       [ 0.,  0.,  1.]])

In [31]:
ones3

array([ 1.,  1.,  1.])

In [32]:
ones3 * np.diag(ones3)*5

array([[ 5.,  0.,  0.],
       [ 0.,  5.,  0.],
       [ 0.,  0.,  5.]])